### ISSUE TITLE
Use proper dependency constraints

### ISSUE THREAD

**Issue by thewilkybarkid** [elifesciences/proofreader-php#1]
`@stable` isn't safe to use.

**Comment by giorgiosironi** [comment]
Should we go for `^major+minor` like `^2.1`?

**Comment by thewilkybarkid** [comment]
Yeah, and go for as open as possible (eg `^2.1 || ^3.0`).

**Comment by giorgiosironi** [comment]
It seems that there is only a supported major version for these packages (with the exception of PHPUnit which is not a `require` but `require_dev`, so I'm supporting all the future releases of these tested major versions.

**Comment by thewilkybarkid** [comment]
Was fixed in 0ae4d0d92fa5c545f010dee0fbfc0c346611d653.
